# 根据动画实测
operations:
  # 终结技动画期间, 失衡不会动
  - op_name: "设置状态"
    state: "自定义-动作不打断"
    seconds: 3.5
  - op_name: "设置状态"
    state: "自定义-失衡时间"
    seconds_add: -2
  - op_name: "等待秒数"
    seconds: 0.10
  - op_name: "按键-终结技"
    post_delay: 0.1
    repeat: 5
  - op_name: "等待秒数"
    seconds: 3