operations:
  # 短暂蓄力
  - op_name: "按键-普通攻击"
    way: "按下"
    press: 0.2
  - op_name: "等待秒数"
    seconds: 0.1
  # 按特殊技触发追碾，并立即提升蓄力等级
  - op_name: "按键-特殊攻击"
  - op_name: "等待秒数"
    seconds: 0.5
  # 按普攻发动满蓄力下砸
  - op_name: "按键-普通攻击"
  - op_name: "等待秒数"
    seconds: 1.8