operations:
  # 根据动画实测，连携技总无敌时间与其它S级角色一致为2秒，如需微调请重新录像测定
  - op_name: "设置状态"
    state: "自定义-连携换人"
    seconds_add: -1
  - op_name: "设置状态"
    state: "自定义-动作不打断"
    seconds: 2
  - op_name: "等待秒数"
    seconds: 2
