# 根据动画实测，待补充
operations:
  - op_name: "按键-特殊攻击"
    post_delay: 0.1
    repeat: 5
  - op_name: "按键-普通攻击"
    post_delay: 0.1
    repeat: 15
  - op_name: "按键-特殊攻击"
    post_delay: 0.1
    repeat: 20
  - op_name: "按键-普通攻击"
    post_delay: 0.1
    repeat: 10
  - op_name: "按键-特殊攻击"
    post_delay: 0.1
    repeat: 20
  - op_name: "按键-特殊攻击-按下"
  - op_name: "等待秒数"
    seconds: 1.0
  - op_name: "按键-特殊攻击-松开"
  - op_name: "清除状态"
    state: "自定义-无视闪光"
  - op_name: "设置状态"
    state: "自定义-合轴时间"
  - op_name: "等待秒数"
    seconds: 1.0
