# 根据动画实测，待补充
operations:
  - op_name: "按键-特殊攻击"
    post_delay: 0.1
    repeat: 10
  - op_name: "按键-普通攻击"
    post_delay: 0.1
    repeat: 10
  - op_name: "按键-特殊攻击"
    post_delay: 0.1
    repeat: 27
  - op_name: "按键-普通攻击"
    post_delay: 0.1
    repeat: 8
  - op_name: "按键-特殊攻击-按下"
  - op_name: "等待秒数"
    seconds: 3.0
