# 根据动画实测
operations:
  - op_name: "设置状态"
    state: "自定义-动作不打断"
    seconds: 5
  - op_name: "按键-普通攻击-按下"
  - op_name: "等待秒数"
    seconds: 3
  - op_name: "按键-普通攻击-松开"
  - op_name: "等待秒数"
    seconds: 1.2
  - op_name: "设置状态"
    state: "自定义-合轴时间"
  - op_name: "等待秒数"
    seconds: 0.8
