# 根据动画实测，动画持续2秒
operations:
  - op_name: "设置状态"
    state: "自定义-爱丽丝-蓄力中"
    seconds: 4.5
  - op_name: "设置状态"
    state: "自定义-无视闪光"
    seconds: 1
  - op_name: "设置状态"
    state: "自定义-动作不打断"
    seconds: 4.5
  - op_name: "按键-普通攻击-按下"