# 根据动画实测，动画持续2秒
operations:
  - op_name: "设置状态"
    state: "自定义-失衡时间"
    seconds_add: -2.4
  - op_name: "设置状态"
    state: "自定义-动作不打断"
    seconds: 4.8
  - op_name: "按键-终结技"
    post_delay: 0.1
    repeat: 28
  - op_name: "等待秒数"
    seconds: 2.0