# 长按强化特殊技 - 送客
operations:
  - op_name: "设置状态"
    state: "自定义-动作不打断"
    seconds: 2
  - op_name: "按键-普通攻击-松开"
  - op_name: "等待秒数"
    seconds: 0.2
  - op_name: "按键-普通攻击-按下"
  - op_name: "等待秒数"
    seconds: 2