# 般岳-终结技-撼天动地
# 释放大范围火属性伤害
# 非怒相状态下使用可回复60点嗔火
operations:
  - op_name: "设置状态"
    state: "自定义-失衡时间"
    seconds_add: -1
  - op_name: "设置状态"
    state: "自定义-动作不打断"
    seconds: 6
  - op_name: "按键-终结技"
    post_delay: 0.1
    repeat: 10
  - op_name: "等待秒数"
    seconds: 5
  - op_name: "清除状态"
    state_list: ["自定义-动作不打断"]
