# 般岳-普通攻击-崔巍（重击4连）
# 非怒相状态下的重击连招，用于积攒嗔火
# 长按普攻进行重击
operations:
  - op_name: "按键-普通攻击-按下"
  - op_name: "等待秒数"
    seconds: 0.5
  - op_name: "按键-普通攻击-松开"
  - op_name: "按键-普通攻击-按下"
  - op_name: "等待秒数"
    seconds: 0.5
  - op_name: "按键-普通攻击-松开"
  - op_name: "按键-普通攻击-按下"
  - op_name: "等待秒数"
    seconds: 0.5
  - op_name: "按键-普通攻击-松开"
  - op_name: "按键-普通攻击-按下"
  - op_name: "等待秒数"
    seconds: 0.5
  - op_name: "按键-普通攻击-松开"
  - op_name: "等待秒数"
    seconds: 0.3
