# 般岳-普通攻击-焚身
# 嗔火≥120时长按A进入怒相状态
# 进入怒相后获得4点山威
operations:
  - op_name: "设置状态"
    state: "自定义-般岳-怒相"
    seconds: 30
  - op_name: "按键-普通攻击-按下"
  - op_name: "等待秒数"
    seconds: 1.2
  - op_name: "按键-普通攻击-松开"
  - op_name: "等待秒数"
    seconds: 0.3
