# 般岳-连携技-怒焰
# 连携技触发后的攻击
# 若嗔火满则可直接进入怒相状态
operations:
  - op_name: "设置状态"
    state: "自定义-失衡时间"
    seconds_add: -1
  - op_name: "设置状态"
    state: "自定义-动作不打断"
    seconds: 4
  - op_name: "等待秒数"
    seconds: 3.5
  - op_name: "清除状态"
    state_list: ["自定义-动作不打断"]
