# 连招：e接第3段a，可连接使用，即eaea
operations:
  - op_name: "设置状态"
    state: "自定义-动作不打断"
    seconds: 1
  - op_name: "按键-特殊攻击"
    post_delay: 0.1
    repeat: 5
  - op_name: "按键-普通攻击"
    post_delay: 0.1
    repeat: 24