# 根据动画实测，动画持续2秒
operations:
  - op_name: "设置状态"
    state: "自定义-动作不打断"
    seconds: 4.5
  - op_name: "清除状态"
    state: "自定义-零号安比-白雷"
  - op_name: "设置状态"
    state: "自定义-零号安比-白雷"
    add: 990
  - op_name: "按键-特殊攻击-按下"
  - op_name: "等待秒数"
    seconds: 1.5
  #雷切
  - op_name: "按键-普通攻击"
    post_delay: 0.1
    repeat: 15
  #三突刺
  - operation_template: "零号安比-特殊技突进"
  - op_name: "设置状态"
    state: "自定义-合轴时间"
