# 根据动画实测，动画持续2秒
operations:
  - op_name: "设置状态"
    state: "自定义-失衡时间"
    seconds_add: -2.6
  - op_name: "设置状态"
    state: "自定义-动作不打断"
    seconds: 5
  - op_name: "设置状态"
    state: "自定义-零号安比-白雷"
    add: 990
  - op_name: "按键-终结技"
    post_delay: 0.1
    repeat: 25
  - op_name: "等待秒数"
    seconds: 2.4
  - operation_template: "零号安比-特殊技突进"