sub_dir: agent_state
template_id: yeshunguang_qingming_ex_3_2
template_name: 角色状态-叶瞬光-青溟剑势白-32
template_shape: multi_rect
auto_mask: true
point_list:
- 562, 101
- 565, 103
- 579, 101
- 581, 104
- 595, 101
- 598, 104
- 611, 101
- 614, 103
- 627, 101
- 631, 104
- 644, 101
- 646, 104
