template_name: "卢西娅-暗破检测"
handlers:
  - states: "[卢西娅-特殊技可用] & [卢西娅-梦境值]{0,0} & [后台-卢西娅]"
    debug_name: "卢西娅进场先开暗破"
    operations:
      - op_name: "按键-切换角色"
        agent_name: "卢西娅"
      - operation_template: "卢西娅-强化特殊技合轴"