template_name: "琉音-送客决策"
handlers:
  - states: "[琉音-客诉]{1, 1} & [琉音-好评]{90, 120} & ([自定义-失衡时间, 1, 15] | ([叶瞬光-青溟剑势-红]{0,3} & [叶瞬光-常态]{1,1}))"
    interrupt_states: "![前台-琉音]"
    operations:
      - op_name: "按键-切换角色"
        agent_name: "琉音"
      - op_name: "等待秒数"
        seconds: 0.5
      - op_name: "设置状态"
        state: "自定义-琉音-连携转终结技"
      - op_name: "清除状态"
        state: "自定义-琉音-投诉"
      - operation_template: "琉音-送客(长按强化特殊技)"
