# 连携后摇等待时间各角色不同 由后续动作控制
handlers:
  - states: "[连携技-1-强攻]"
    operations:
      - operation_template: "连携-左"
      - op_name: "设置状态"
        state: "自定义-失衡时间"
  - states: "[连携技-2-强攻]"
    operations:
      - operation_template: "连携-右"
      - op_name: "设置状态"
        state: "自定义-失衡时间"