# 连携后摇等待时间各角色不同 由后续动作控制
handlers:
  # 苍角别把展旗覆盖掉了
  - states: "[连携技-1-支援] & ![连携技-1-苍角] & ![连携技-1-耀嘉音]"
    operations:
      - operation_template: "连携-左"
      - op_name: "设置状态"
        state: "自定义-失衡时间"
  - states: "[连携技-2-支援] & ![连携技-2-苍角] & ![连携技-2-耀嘉音]"
    operations:
      - operation_template: "连携-右"
      - op_name: "设置状态"
        state: "自定义-失衡时间"