# 连携后摇等待时间各角色不同 由后续动作控制
handlers:
  # 连携条件
  - states: "[连携技-1-邦布]"
    sub_handlers:
      - states: "[连携技-2-强攻]"
        operations: &link_ops
          - operation_template: "连携-左"
          - op_name: "设置状态"
            state: "自定义-失衡时间"
            seconds: 1
          - op_name: "设置状态"
            state: "自定义-动作不打断"
            seconds: 1
      - states: "[连携技-2-异常]"
        operations: *link_ops
