# 闪避普攻 普攻后摇等待时间各角色不同 由后续动作控制
handlers:
  - states: "![自定义-连携跳过, 0, 3]"
    sub_handlers:
    - states: "[自定义-琉音-连携转终结技,0,99] & [前台-琉音]"
      debug_name: "是送客时间呢"
      sub_handlers:
        - states: "[连携技-1-命破] | [连携技-1-强攻]"
          operations:
          - operation_template: "连携-左"
        - states: "[连携技-2-命破] | [连携技-2-强攻]"
          operations:
          - operation_template: "连携-右"
        - states: "[连携技-1-支援] | [连携技-1-异常]"
          operations:
          - operation_template: "连携-左"
        - states: "[连携技-2-支援] | [连携技-2-异常]"
          operations:
          - operation_template: "连携-右"
        - states: ""
          operations:
          - operation_template: "连携-左"

    - state_template: "连携模板-前置角色"

    - states: "[前台-仪玄]"
      sub_handlers:
        - state_template: "连携模板-跳过"

    - states: "[前台-苍角] & [自定义-失衡时间, 0, 3]"
      sub_handlers:
        - state_template: "连携模板-强攻"
        - state_template: "连携模板-异常"
        - state_template: "连携模板-跳过"

    - states: "[前台-强攻] & [前台-命破] & [自定义-失衡时间, 0, 3]"
      sub_handlers:
        - state_template: "连携模板-命破"
        - state_template: "连携模板-强攻"
        - state_template: "连携模板-支援"
        - state_template: "连携模板-跳过"

    - states: ""
      sub_handlers:
        - state_template: "连携模板-命破"
        - state_template: "连携模板-支援"
        - state_template: "连携模板-异常"
        - state_template: "连携模板-强攻"
        - state_template: "连携模板-后置角色"
        - state_template: "连携模板-跳过"