template_name: "速切模板-叶瞬光"
handlers:
  - states: "[前台-叶瞬光]"
    interrupt_states: "[前台-能量, 0, 0.1] & ![前台-叶瞬光]"
    sub_handlers:
      - states: "[自定义-黄光切人, 0, 1]"
        operations:
          - operation_template: "叶瞬光-支援攻击"

      - states: "[自定义-红光闪避, 0, 1] & [叶瞬光-常态]{1,1}"
        operations:
          - operation_template: "叶瞬光-格挡"

      - states: "[自定义-连携换人, 0, 1]"
        sub_handlers:
          - states: "[叶瞬光-常态]{0,0}"
            interrupt_states: "[叶瞬光-常态]{1,1}"
            operations:
              - op_name: "设置状态"
                state: "自定义-无视闪光"
                seconds: 15
              - op_name: "等待秒数"
                seconds: 3
              - op_name: "设置状态"
                state: "自定义-叶瞬光-在天"
          - states: "[叶瞬光-常态]{1,1}"
            interrupt_states: "[叶瞬光-常态]{0,0}"
            operations:
              - operation_template: "叶瞬光-连携攻击"

      # 防呆
      - states: "([按键-切换角色-下一个, 0, 0.3]|[按键-切换角色-上一个, 0, 0.3])"
        debug_name: "切人后等待"
        sub_handlers:
          - states: "[叶瞬光-常态]{1,1} & [叶瞬光-青溟剑势-红]{6,6}"
            interrupt_states: "[叶瞬光-青溟剑势-白]{6,6}"
            debug_name: "自动变身"
            operations:
              - op_name: "设置状态"
                state: "自定义-无视闪光"
                seconds: 15
              - op_name: "设置状态"
                state: "自定义-叶瞬光-在天"
              - op_name: "等待秒数"
                seconds: 2

          - states: "[叶瞬光-常态]{0,0}"
            interrupt_states: "[叶瞬光-常态]{1,1}"
            operations:
              - op_name: "设置状态"
                state: "自定义-叶瞬光-在地"
              - op_name: "等待秒数"
                seconds: 0.3

          - states: "[按键可用-快速支援, 0, 0.3]"
            operations:
              - op_name: "等待秒数"
                seconds: 0.3

          - states: ""
            operations:
              - op_name: "等待秒数"
                seconds: 0.3

      - states: "[自定义-叶瞬光-收刀]"
        debug_name: "收到结束可以速切了"
        sub_handlers:
          - states: "[叶瞬光-常态]{1,1} | [叶瞬光-能量]{0,5}"
            operations:
              - op_name: "清除状态"
                state: "自定义-无视闪光"
              - op_name: "清除状态"
                state: "自定义-叶瞬光-收刀"
              - op_name: "设置状态"
                state: "自定义-合轴时间"

          - states: "[叶瞬光-能量]{100,120}"
            debug_name: "误判"
            operations:
              - op_name: "清除状态"
                state: "自定义-叶瞬光-收刀"

          - states: ""
            interrupt_states: "[叶瞬光-常态]{1,1} | [叶瞬光-能量]{0,5} | [叶瞬光-能量]{100,120}"
            debug_name: "坐等收刀结束"
            operations:
              - op_name: "等待秒数"
                seconds: 3

      - states: "[叶瞬光-常态]{1,1}"
        interrupt_states: "[叶瞬光-常态]{0,0}"
        debug_name: "常态-技能优先"
        sub_handlers:
          - states: "[叶瞬光-青溟剑势-红]{6,6} | [叶瞬光-能量, 1, 99]"
            operations:
              - op_name: "设置状态"
                state: "自定义-无视闪光"
                seconds: 15
              - operation_template: "叶瞬光-变身"
          - states: "[叶瞬光-终结技可用] & [叶瞬光-青溟剑势-红]{0,3}"
            operations:
              - operation_template: "叶瞬光-终结技-起"
          - states: "[叶瞬光-特殊技可用] & ([叶瞬光-青溟剑势-红]{4,6} | [叶瞬光-能量]{115,120})"
            operations:
              - operation_template: "叶瞬光-强化特殊攻击"
          - states: ""
            interrupt_states: "[叶瞬光-终结技可用] | [叶瞬光-特殊技可用] | ![叶瞬光-常态] | [叶瞬光-青溟剑势-红]{6,6}"
            operations:
              - operation_template: "叶瞬光-普通攻击"

      - states: "[叶瞬光-常态]{0,0}"
        interrupt_states: "[叶瞬光-常态]{1,1}"
        debug_name: "非常态-强化特殊攻击"
        sub_handlers:
          - states: "[叶瞬光-能量]{117,120}"
            interrupt_states: "[叶瞬光-常态]{100,117}"
            debug_name: "等待变身就绪"
            operations:
              - op_name: "设置状态"
                state: "自定义-无视闪光"
                seconds: 15
              - op_name: "按键-特殊攻击-松开"
              - op_name: "按键-普通攻击-松开"
              - op_name: "等待秒数"
                seconds: 0.7

          - states: "[叶瞬光-青溟剑势-白]{0,0} & [叶瞬光-能量]{0,100}  | [叶瞬光-能量]{0,20}"
            interrupt_states: "[叶瞬光-青溟剑势-白]{1,6} & ![叶瞬光-能量]{0,20} | [叶瞬光-能量]{0,5}"
            operations:
              - op_name: "设置状态"
                state: "自定义-叶瞬光-收刀"
              - operation_template: "叶瞬光-乱砍"

          - states: "[叶瞬光-青溟剑势-白]{1,5} | [自定义-叶瞬光-在地]"
            interrupt_states: "[叶瞬光-青溟剑势-白]{0,0} | [叶瞬光-青溟剑势-白]{6,6} | [叶瞬光-能量]{0,20}"
            operations:
              - op_name: "清除状态"
                state: "自定义-叶瞬光-在地"
              - operation_template: "叶瞬光-飞天连段"

          - states: "[叶瞬光-青溟剑势-白]{6,6} & [叶瞬光-能量]{100,120} | [自定义-叶瞬光-在天]"
            interrupt_states: "[叶瞬光-能量]{0,20} | [叶瞬光-能量]{115,120}"
            operations:
              - op_name: "清除状态"
                state: "自定义-叶瞬光-在天"
              - op_name: "设置状态"
                state: "自定义-无视闪光"
                seconds: 15
              - operation_template: "叶瞬光-eaeeeaE"
