template_name: "速切模板-伊德海莉"
handlers:
  - states: "[前台-伊德海莉]"
    interrupt_states: "[前台-能量, 0, 0.1] & ![前台-伊德海莉]"
    sub_handlers:
      - states: "[自定义-连携换人, 0, 0.5]"
        operations:
          - op_name: "清除状态"
            state_list: ["自定义-伊德海莉-追碾状态" , "自定义-伊德海莉-旋转状态" , "自定义-伊德海莉-蓄力中"]
          - operation_template: "伊德海莉-连携攻击"

      - states: "[自定义-黄光切人, 0, 1]"
        operations:
          - op_name: "清除状态"
            state_list: ["自定义-伊德海莉-追碾状态" , "自定义-伊德海莉-旋转状态" , "自定义-伊德海莉-蓄力中"]
          - operation_template: "伊德海莉-支援攻击"

      - states: "[自定义-红光闪避, 0, 1]"
        sub_handlers:
          - states: "[自定义-伊德海莉-蓄力中,0,2] | [自定义-伊德海莉-旋转状态,0,2]"
            debug_name: "红光蓄力中进入追碾状态"
            operations:
              - op_name: "按键-特殊攻击"
              - op_name: "清除状态"
                state_list:
                  ["自定义-伊德海莉-蓄力中", "自定义-伊德海莉-旋转状态"]
              - op_name: "设置状态"
                state: "自定义-伊德海莉-追碾状态"
              - op_name: "等待秒数"
                seconds: 1

          - states: ""
            debug_name: "红光非蓄力中使用闪A"
            operations:
              - op_name: "按键-闪避"
              - op_name: "等待秒数"
                seconds: 0.1
              - op_name: "按键-普通攻击"
              - op_name: "等待秒数"
                seconds: 1

      # 防呆
      - states: "([按键-切换角色-下一个, 0, 0.3]|[按键-切换角色-上一个, 0, 0.3])"
        debug_name: "切人后等待"
        sub_handlers:
          - states: "[按键可用-快速支援, 0, 0.5]"
            operations:
              - op_name: "清除状态"
                state_list: ["自定义-伊德海莉-追碾状态" , "自定义-伊德海莉-旋转状态" , "自定义-伊德海莉-蓄力中"]
              - op_name: "等待秒数"
                seconds: 0.5
          - states: ""
            operations:
              - op_name: "清除状态"
                state_list: ["自定义-伊德海莉-追碾状态" , "自定义-伊德海莉-旋转状态" , "自定义-伊德海莉-蓄力中"]
              - op_name: "等待秒数"
                seconds: 0.3

      - states: "[自定义-伊德海莉-追碾状态, 0, 2]"
        interrupt_states: "[伊德海莉-蓄力段数]{0, 0}"
        debug_name: "追碾状态连点普攻"
        operations:
          - op_name: "清除状态"
            state_list: ["自定义-伊德海莉-追碾状态" , "自定义-伊德海莉-旋转状态"]
          - op_name: "按键-普通攻击"
            post_delay: 0.2
            repeat: 50

      - states: "[自定义-连携换人, 0, 10]"
        sub_handlers:
          - states: "[伊德海莉-终结技可用]"
            operations:
              - operation_template: "伊德海莉-终结技"

          - states: "[自定义-伊德海莉-蓄力中, 0, 2] & [伊德海莉-特殊技可用]"
            debug_name: "失衡期间直接追碾"
            operations:
              - op_name: "按键-特殊攻击"
              - op_name: "清除状态"
                state_list: ["自定义-伊德海莉-蓄力中"]
              - op_name: "设置状态"
                state: "自定义-伊德海莉-追碾状态"

      - states: "[自定义-伊德海莉-旋转状态, 2, 99]"
        interrupt_states: ""
        debug_name: "旋转状态结束"
        operations:
          - op_name: "清除状态"
            state_list: ["自定义-伊德海莉-旋转状态"]
          - op_name: "设置状态"
            state: "自定义-伊德海莉-追碾状态"

      - states: "[自定义-伊德海莉-旋转状态, 0, 2]"
        interrupt_states: "[伊德海莉-蓄力段数]{0, 0}"
        debug_name: "旋转状态连按普攻"
        operations:
          - op_name: "等待秒数"
            seconds: 2

      - states: "[自定义-伊德海莉-蓄力中, 0, 2] & [伊德海莉-蓄力段数]{85, 100}"
        debug_name: "蓄力满了松开"
        operations:
          - op_name: "清除状态"
            state_list: ["自定义-伊德海莉-蓄力中"]
          - op_name: "设置状态"
            state: "自定义-伊德海莉-旋转状态"

      - states: "[伊德海莉-蓄力段数]{0, 0}"
        interrupt_states: "[伊德海莉-蓄力段数]{85, 100}"
        debug_name: "长按普攻蓄力"
        operations:
          - op_name: "清除状态"
            state_list: ["自定义-伊德海莉-旋转状态"]
          - op_name: "按键-普通攻击-按下"
          - op_name: "按键-移动-前-按下"
          - op_name: "按键-移动-右-按下"
          - op_name: "设置状态"
            state: "自定义-伊德海莉-蓄力中"
          - op_name: "等待秒数"
            seconds: 0.5

      - states: ""
        interrupt_states: "[伊德海莉-蓄力段数]{0, 0}"
        debug_name: "长按普攻蓄力"
        operations:
          - op_name: "等待秒数"
            seconds: 1
