project_name: "ZenlessZoneZero-OneDragon"
python_version: "3.11"
github_homepage: "https://github.com/OneDragon-Anything/ZenlessZoneZero-OneDragon"
github_https_repository: "https://github.com/OneDragon-Anything/ZenlessZoneZero-OneDragon.git"
github_ssh_repository: "git@github.com:OneDragon-Anything/ZenlessZoneZero-OneDragon.git"
gitee_https_repository: "https://gitee.com/OneDragon-Anything/ZenlessZoneZero-OneDragon.git"
gitee_ssh_repository: "git@gitee.com:OneDragon-Anything/ZenlessZoneZero-OneDragon.git"
project_git_branch: "main"
screen_standard_width: 1920
screen_standard_height: 1080
pip_source: "https://pypi.tuna.tsinghua.edu.cn/simple"
notice_url: "https://one-dragon.com/notice/zzz/notice.json"
qq_link: "https://pd.qq.com/g/onedrag00n"
quick_start_link: "http://one-dragon.com/zzz/zh/quickstart.html"
home_page_link: "https://one-dragon.com/zzz/zh/home.html"
doc_link: "https://docs.qq.com/doc/p/7add96a4600d363b75d2df83bb2635a7c6a969b5"