sub_dir: agent_state
template_id: yeshunguang_qingming_3_2
template_name: 角色状态-叶瞬光-青溟剑势红-32
template_shape: multi_rect
auto_mask: true
point_list:
- 580, 101
- 581, 103
- 589, 102
- 590, 103
- 599, 102
- 600, 103
- 609, 102
- 610, 103
- 618, 102
- 619, 103
- 628, 102
- 629, 103
