# 该文件用于演示所有可用参数, 请以此为蓝本裁剪自己专属的空洞配置
# 更详尽的参数请参考
# assets\game_data\hollow_zero\lost_void\lost_void_artifact_data.yml

# 自动战斗配置, 建议不要改动, 直接用通配, 有问题上报.
auto_battle: 全配队通用

# 区域类型优先级, 优先级从上到下, 相同的区域类型会按照优先级顺序进行选择
# 当前按性价比进行了排序, 建议全自动少选择突发事件或降低优先级
region_type_priority:
  - 战斗-武备
  - 挑战-无伤
  - 邦布商店
  - 挚交会谈
  - 战斗-道中危机
  - 战斗-终结之役
  - 战斗-硬币
  - 挑战-限时
  - 战斗-鸣徽

# 藏品优先级, 可以设置多个, 优先级从上到下, 相同的藏品会按照优先级顺序进行购买
# 这里仅做组合示例
# 建议不要设置太多, 否则会导致武备刷取缓慢
artifact_priority:
  - 机敏
  - 终结
  - 通用
  - 绝境
  - 契合
  - 异常·击破
  - 星见雅
  - 星见雅 花间雀
  - 艾莲
  - 月城柳
  - 比利
  - 卡牌
  - 绝境 战斗维生包
  - 无详情 获得鸣徽

# 藏品第二优先级
artifact_priority_2:
  - 异常·击破 混沌量杯
  - 通用 三相战斗陀螺
  - 绝境

# 只购买第一个优先级
# 刷新多少次数内, 只购买第一个优先级的藏品
buy_only_priority_1: 2

# 只购买第二个优先级
# 刷新多少次数内, 只购买第二个优先级的藏品
buy_only_priority_2: 1

# 周期增益
# 可选参数: 第一个, 第二个, 第三个
period_buff_no: 第一个

# 调查策略
# 选择使用的调查战略名称, 对应内部加载的战略列表条目, 影响进入副本时的战略选择逻辑
investigation_strategy: 攻其不备战略

# 追新模式
# 开启后优先选择未满级的调查战略
chase_new_mode: true

# 优先选择NEW！藏品
# 开启后在藏品筛选时对未记录过的新藏品给予额外考虑
artifact_priority_new: true

# 商店-使用血量购买
# 关闭后不允许在邦布商店用当前角色血量作为货币购买
store_blood: false