sub_dir: agent_state
template_id: yeshunguang_qingming_3_3
template_name: 角色状态-叶瞬光-青溟剑势红-33
template_shape: multi_rect
auto_mask: true
point_list:
- 761, 102
- 762, 103
- 771, 102
- 772, 103
- 781, 102
- 782, 103
- 790, 102
- 791, 103
- 799, 102
- 801, 103
- 809, 102
- 810, 103
