sub_dir: agent_state
template_id: yeshunguang_qingming_3_3
template_name: 角色状态-叶瞬光-青溟剑势红-33
template_shape: multi_rect
auto_mask: true
point_list:
- 761, 101
- 763, 104
- 771, 101
- 773, 104
- 780, 101
- 782, 104
- 789, 101
- 792, 104
- 799, 101
- 802, 104
- 809, 101
- 811, 104
