idx: 1
op_list:
- data:
  - '613'
  - '2046'
  op_type: move
- data:
  - '571'
  - '1994'
  op_type: move
- data:
  - '551'
  - '1955'
  op_type: move
- data:
  - '546'
  - '1871'
  op_type: move
- data:
  - '544'
  - '1844'
  op_type: move
- data:
  - '544'
  - '1810'
  op_type: move
- data:
  - '626'
  - '1804'
  op_type: move
- data:
  - '634'
  - '1807'
  op_type: move
- data:
  - '634'
  - '1761'
  op_type: move
- data:
  - '650'
  - '1737'
  op_type: move
- data:
  - '679'
  - '1768'
  op_type: move
- data:
  - '658'
  - '1792'
  op_type: move
tp_area_id: production_area_building_east_side
tp_name: 中央制造区入口
