idx: 2
op_list:
- data:
  - '867'
  - '1436'
  op_type: move
- data:
  - '867'
  - '1356'
  op_type: move
- data:
  - '867'
  - '1140'
  op_type: move
- data:
  - '836'
  - '1094'
  op_type: move
- data:
  - '792'
  - '1148'
  op_type: move
tp_area_id: production_area_building_east_side
tp_name: 物流通道
